micronaut:
  application:
    name: micronautsample
  metrics:
    export:
      azuremonitor:
        enabled: true
        instrumentationKey: ${AZUREMONITOR_INSTRUMENTATION_KEY}
        step: PT1M
    enabled: true
